[package]
name = "kampr-term"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
vte = "0.15"

[dev-dependencies]
serde_json.workspace = true
