[package]
name = "kampr-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kampr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
kampr-auth = { path = "../kampr-auth" }
kampr-node = { path = "../kampr-node" }
qrcode.workspace = true
time.workspace = true
url.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
